In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
print(pd.__version__, np.__version__, mpl.__version__)

1.0.5 1.18.5 3.2.2


In [3]:
dataset = pd.read_csv('Bank_Personal_Loan_Modelling.csv')
dataset.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
dataset = dataset.drop(['ID', 'ZIP Code'], axis = 1)
dataset.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [5]:
x = dataset.iloc[:, :7]
x.shape

(5000, 7)

In [29]:
y = dataset.iloc[:, 7]
y.shape

(5000,)

In [7]:
# Number of unique in each column?
for i in x.columns:
    print('Unique values in cloumn {} is: {}'.format(i, np.unique(x[i])))

Unique values in cloumn Age is: [23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46
 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67]
Unique values in cloumn Experience is: [-3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
Unique values in cloumn Income is: [  8   9  10  11  12  13  14  15  18  19  20  21  22  23  24  25  28  29
  30  31  32  33  34  35  38  39  40  41  42  43  44  45  48  49  50  51
  52  53  54  55  58  59  60  61  62  63  64  65  68  69  70  71  72  73
  74  75  78  79  80  81  82  83  84  85  88  89  90  91  92  93  94  95
  98  99 100 101 102 103 104 105 108 109 110 111 112 113 114 115 118 119
 120 121 122 123 124 125 128 129 130 131 132 133 134 135 138 139 140 141
 142 143 144 145 148 149 150 151 152 153 154 155 158 159 160 161 162 163
 164 165 168 169 170 171 172 173 174 175 178 179 180 181 182 183 184 185
 188 189 190 191 192 193 194

In [12]:
# Number of people with zero mortgage?
len(x[x['Mortgage'] == 0])

3462

In [14]:
#Number of people with zero credit card spending per month?
len(dataset[dataset['CreditCard'] == 0])

3530

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x)
x = sc.transform(x)
x.shape

(5000, 7)

In [32]:
y = dataset.iloc[:, 7]
y.shape

(5000,)

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,
                                                    random_state = 0) 

In [34]:
x_train.shape

(3500, 7)

In [35]:
x_test.shape

(1500, 7)

In [36]:
y_train.shape

(3500,)

In [37]:
y_test.shape

(1500,)

In [38]:
from sklearn.linear_model import LogisticRegression

In [39]:
log_r = LogisticRegression()

In [40]:
log_r.fit(x_train, y_train)

LogisticRegression()

In [41]:
pred = log_r.predict(x_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [44]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

In [45]:
accuracy_score(y_test, pred)*100

95.39999999999999

In [46]:
confusion_matrix(y_test, pred)

array([[1353,   19],
       [  50,   78]], dtype=int64)

In [47]:
classification_report(y_test, pred, target_names=['yes', 'no'])

'              precision    recall  f1-score   support\n\n         yes       0.96      0.99      0.98      1372\n          no       0.80      0.61      0.69       128\n\n    accuracy                           0.95      1500\n   macro avg       0.88      0.80      0.83      1500\nweighted avg       0.95      0.95      0.95      1500\n'

In [48]:
log_r.predict([[26, 20, 50, 3, 1.3, 2, 78], [56, 40, 60, 3, 1.6, 4, 150],
              [0, 0 , 0 , 0, 0, 0, 0]])

array([1, 1, 0], dtype=int64)